@baseUrl = http://localhost:3000/api/v0
@accessToken = PEGA_AQUI_EL_ACCESS_TOKEN

### CREATE nueva Receta
POST {{baseUrl}}/recetas
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_cliente": 2,
    "doctor_remitente": "Ana Torres",
    "ruc_doctor_remitente": "1712345678001",
    "hospital_remitente": "Clinica Norte",
    "telefono_hospital": "022345678",
    "correo": "contacto@clinicanorte.com",
    "codigo": 1001,
    "fecha": "2026-04-14"
}

### READ una Receta
GET {{baseUrl}}/recetas/1
Authorization: Bearer {{accessToken}}

### READ todas las Recetas
GET {{baseUrl}}/recetas/all
Authorization: Bearer {{accessToken}}

### UPDATE una Receta
PUT {{baseUrl}}/recetas/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_cliente": 1,
    "doctor_remitente": "Ana Torres",
    "hospital_remitente": "Clinica Central",
    "telefono_hospital": "022000111",
    "codigo": 1002,
    "fecha": "2026-04-15"
}

### DELETE una Receta
DELETE {{baseUrl}}/recetas/1
Authorization: Bearer {{accessToken}}
