@baseUrl = http://localhost:3000/api/v0
@RefreshToken =

### LOGIN (cuenta existente)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "rubenfeng12@gmail.com",
    "password": "admin123"
}

### SIGNUP (crear nueva cuenta)
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "rubenfeng12@gmail.com",
    "password": "admin123"
}

### REFRESH TOKEN (usar refresh_token del login en Authorization)
POST {{baseUrl}}/auth/refresh-token
Authorization: Bearer ailpar2qhekg
Content-Type: application/json

### EJEMPLO CONSULTA PROTEGIDA (usar access_token del login)
GET {{baseUrl}}/accesos/all
Authorization: Bearer {{login.response.body.$.session.access_token}}
